- name: backend configure
  hosts: backend
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y
    
  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install packages
    ansible.builtin.package:
       name: "{{ item }}"
       state: present
    loop:
    - nodejs
    - mysql 

  - name: add user
    ansible.builtin.user:
      name: expense 

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: download backend packages
    ansible.builtin.get_url:
      url: curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: extract code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
  
  - name: install dependies
    ansible.builtin.command: install npm
    ars:
     chdir: /app
  
  - name: copy file 
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service

  - name: ansible to install pymysql
    ansible.builtin.pip:
      name:
      - PyMySQL
      executable: pip3.9

  - name: import mysql data
    community.mysql.mysql_db:
      login_user: root
      login_password: ExpenseApp@1
      login_host: 172.31.87.133
      target: /app/schema/backend.sql
      name: all
      state: import

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
      state: restarted
      name: backend

  

       