- name: variables to print
  hosts: web
  become: yes
  vars:
    COURSE: "devops with aws"
    DURATION: "120 hr"
    TRINEER: "siva kumar"
  
  tasks:
  - name: variables to print
    ansible.builtin.debug:
         msg: " i am learing {{ COURSE }} duration is  {{ DURATION}} {{ TRINEER}}"
  
  - name: task level variables
    vars:
      COURSE: " ansible"
    ansible.builtin.debug:
      msg: " i am learing {{ COURSE }} duration is  {{ DURATION}} {{ TRINEER}}"